# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\ucrt64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\ucrt64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\User\Desktop\5bw121

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\User\Desktop\5bw121

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\ucrt64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\ucrt64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\User\Desktop\5bw121\CMakeFiles D:\User\Desktop\5bw121\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\User\Desktop\5bw121\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 5bw12

# Build rule for target.
5bw12: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 5bw12
.PHONY : 5bw12

# fast build rule for target.
5bw12/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/build
.PHONY : 5bw12/fast

battle/ability.o: battle/ability.cpp.o
.PHONY : battle/ability.o

# target to build an object file
battle/ability.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/ability.cpp.o
.PHONY : battle/ability.cpp.o

battle/ability.i: battle/ability.cpp.i
.PHONY : battle/ability.i

# target to preprocess a source file
battle/ability.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/ability.cpp.i
.PHONY : battle/ability.cpp.i

battle/ability.s: battle/ability.cpp.s
.PHONY : battle/ability.s

# target to generate assembly for a file
battle/ability.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/ability.cpp.s
.PHONY : battle/ability.cpp.s

battle/abilityManager.o: battle/abilityManager.cpp.o
.PHONY : battle/abilityManager.o

# target to build an object file
battle/abilityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/abilityManager.cpp.o
.PHONY : battle/abilityManager.cpp.o

battle/abilityManager.i: battle/abilityManager.cpp.i
.PHONY : battle/abilityManager.i

# target to preprocess a source file
battle/abilityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/abilityManager.cpp.i
.PHONY : battle/abilityManager.cpp.i

battle/abilityManager.s: battle/abilityManager.cpp.s
.PHONY : battle/abilityManager.s

# target to generate assembly for a file
battle/abilityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/abilityManager.cpp.s
.PHONY : battle/abilityManager.cpp.s

battle/abilityPanel.o: battle/abilityPanel.cpp.o
.PHONY : battle/abilityPanel.o

# target to build an object file
battle/abilityPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/abilityPanel.cpp.o
.PHONY : battle/abilityPanel.cpp.o

battle/abilityPanel.i: battle/abilityPanel.cpp.i
.PHONY : battle/abilityPanel.i

# target to preprocess a source file
battle/abilityPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/abilityPanel.cpp.i
.PHONY : battle/abilityPanel.cpp.i

battle/abilityPanel.s: battle/abilityPanel.cpp.s
.PHONY : battle/abilityPanel.s

# target to generate assembly for a file
battle/abilityPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/abilityPanel.cpp.s
.PHONY : battle/abilityPanel.cpp.s

battle/actionText.o: battle/actionText.cpp.o
.PHONY : battle/actionText.o

# target to build an object file
battle/actionText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/actionText.cpp.o
.PHONY : battle/actionText.cpp.o

battle/actionText.i: battle/actionText.cpp.i
.PHONY : battle/actionText.i

# target to preprocess a source file
battle/actionText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/actionText.cpp.i
.PHONY : battle/actionText.cpp.i

battle/actionText.s: battle/actionText.cpp.s
.PHONY : battle/actionText.s

# target to generate assembly for a file
battle/actionText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/actionText.cpp.s
.PHONY : battle/actionText.cpp.s

battle/battleEntity.o: battle/battleEntity.cpp.o
.PHONY : battle/battleEntity.o

# target to build an object file
battle/battleEntity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/battleEntity.cpp.o
.PHONY : battle/battleEntity.cpp.o

battle/battleEntity.i: battle/battleEntity.cpp.i
.PHONY : battle/battleEntity.i

# target to preprocess a source file
battle/battleEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/battleEntity.cpp.i
.PHONY : battle/battleEntity.cpp.i

battle/battleEntity.s: battle/battleEntity.cpp.s
.PHONY : battle/battleEntity.s

# target to generate assembly for a file
battle/battleEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/battleEntity.cpp.s
.PHONY : battle/battleEntity.cpp.s

battle/bulletEntity.o: battle/bulletEntity.cpp.o
.PHONY : battle/bulletEntity.o

# target to build an object file
battle/bulletEntity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/bulletEntity.cpp.o
.PHONY : battle/bulletEntity.cpp.o

battle/bulletEntity.i: battle/bulletEntity.cpp.i
.PHONY : battle/bulletEntity.i

# target to preprocess a source file
battle/bulletEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/bulletEntity.cpp.i
.PHONY : battle/bulletEntity.cpp.i

battle/bulletEntity.s: battle/bulletEntity.cpp.s
.PHONY : battle/bulletEntity.s

# target to generate assembly for a file
battle/bulletEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/bulletEntity.cpp.s
.PHONY : battle/bulletEntity.cpp.s

battle/cardVfx.o: battle/cardVfx.cpp.o
.PHONY : battle/cardVfx.o

# target to build an object file
battle/cardVfx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/cardVfx.cpp.o
.PHONY : battle/cardVfx.cpp.o

battle/cardVfx.i: battle/cardVfx.cpp.i
.PHONY : battle/cardVfx.i

# target to preprocess a source file
battle/cardVfx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/cardVfx.cpp.i
.PHONY : battle/cardVfx.cpp.i

battle/cardVfx.s: battle/cardVfx.cpp.s
.PHONY : battle/cardVfx.s

# target to generate assembly for a file
battle/cardVfx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/cardVfx.cpp.s
.PHONY : battle/cardVfx.cpp.s

battle/effectIcon.o: battle/effectIcon.cpp.o
.PHONY : battle/effectIcon.o

# target to build an object file
battle/effectIcon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectIcon.cpp.o
.PHONY : battle/effectIcon.cpp.o

battle/effectIcon.i: battle/effectIcon.cpp.i
.PHONY : battle/effectIcon.i

# target to preprocess a source file
battle/effectIcon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectIcon.cpp.i
.PHONY : battle/effectIcon.cpp.i

battle/effectIcon.s: battle/effectIcon.cpp.s
.PHONY : battle/effectIcon.s

# target to generate assembly for a file
battle/effectIcon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectIcon.cpp.s
.PHONY : battle/effectIcon.cpp.s

battle/effectIconList.o: battle/effectIconList.cpp.o
.PHONY : battle/effectIconList.o

# target to build an object file
battle/effectIconList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectIconList.cpp.o
.PHONY : battle/effectIconList.cpp.o

battle/effectIconList.i: battle/effectIconList.cpp.i
.PHONY : battle/effectIconList.i

# target to preprocess a source file
battle/effectIconList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectIconList.cpp.i
.PHONY : battle/effectIconList.cpp.i

battle/effectIconList.s: battle/effectIconList.cpp.s
.PHONY : battle/effectIconList.s

# target to generate assembly for a file
battle/effectIconList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectIconList.cpp.s
.PHONY : battle/effectIconList.cpp.s

battle/effectLabel.o: battle/effectLabel.cpp.o
.PHONY : battle/effectLabel.o

# target to build an object file
battle/effectLabel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectLabel.cpp.o
.PHONY : battle/effectLabel.cpp.o

battle/effectLabel.i: battle/effectLabel.cpp.i
.PHONY : battle/effectLabel.i

# target to preprocess a source file
battle/effectLabel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectLabel.cpp.i
.PHONY : battle/effectLabel.cpp.i

battle/effectLabel.s: battle/effectLabel.cpp.s
.PHONY : battle/effectLabel.s

# target to generate assembly for a file
battle/effectLabel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/effectLabel.cpp.s
.PHONY : battle/effectLabel.cpp.s

battle/enemyParty.o: battle/enemyParty.cpp.o
.PHONY : battle/enemyParty.o

# target to build an object file
battle/enemyParty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/enemyParty.cpp.o
.PHONY : battle/enemyParty.cpp.o

battle/enemyParty.i: battle/enemyParty.cpp.i
.PHONY : battle/enemyParty.i

# target to preprocess a source file
battle/enemyParty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/enemyParty.cpp.i
.PHONY : battle/enemyParty.cpp.i

battle/enemyParty.s: battle/enemyParty.cpp.s
.PHONY : battle/enemyParty.s

# target to generate assembly for a file
battle/enemyParty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/enemyParty.cpp.s
.PHONY : battle/enemyParty.cpp.s

battle/minigame.o: battle/minigame.cpp.o
.PHONY : battle/minigame.o

# target to build an object file
battle/minigame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/minigame.cpp.o
.PHONY : battle/minigame.cpp.o

battle/minigame.i: battle/minigame.cpp.i
.PHONY : battle/minigame.i

# target to preprocess a source file
battle/minigame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/minigame.cpp.i
.PHONY : battle/minigame.cpp.i

battle/minigame.s: battle/minigame.cpp.s
.PHONY : battle/minigame.s

# target to generate assembly for a file
battle/minigame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/minigame.cpp.s
.PHONY : battle/minigame.cpp.s

battle/party.o: battle/party.cpp.o
.PHONY : battle/party.o

# target to build an object file
battle/party.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/party.cpp.o
.PHONY : battle/party.cpp.o

battle/party.i: battle/party.cpp.i
.PHONY : battle/party.i

# target to preprocess a source file
battle/party.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/party.cpp.i
.PHONY : battle/party.cpp.i

battle/party.s: battle/party.cpp.s
.PHONY : battle/party.s

# target to generate assembly for a file
battle/party.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/party.cpp.s
.PHONY : battle/party.cpp.s

battle/partyManager.o: battle/partyManager.cpp.o
.PHONY : battle/partyManager.o

# target to build an object file
battle/partyManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/partyManager.cpp.o
.PHONY : battle/partyManager.cpp.o

battle/partyManager.i: battle/partyManager.cpp.i
.PHONY : battle/partyManager.i

# target to preprocess a source file
battle/partyManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/partyManager.cpp.i
.PHONY : battle/partyManager.cpp.i

battle/partyManager.s: battle/partyManager.cpp.s
.PHONY : battle/partyManager.s

# target to generate assembly for a file
battle/partyManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/partyManager.cpp.s
.PHONY : battle/partyManager.cpp.s

battle/playerParty.o: battle/playerParty.cpp.o
.PHONY : battle/playerParty.o

# target to build an object file
battle/playerParty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/playerParty.cpp.o
.PHONY : battle/playerParty.cpp.o

battle/playerParty.i: battle/playerParty.cpp.i
.PHONY : battle/playerParty.i

# target to preprocess a source file
battle/playerParty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/playerParty.cpp.i
.PHONY : battle/playerParty.cpp.i

battle/playerParty.s: battle/playerParty.cpp.s
.PHONY : battle/playerParty.s

# target to generate assembly for a file
battle/playerParty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/playerParty.cpp.s
.PHONY : battle/playerParty.cpp.s

battle/targetSelector.o: battle/targetSelector.cpp.o
.PHONY : battle/targetSelector.o

# target to build an object file
battle/targetSelector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/targetSelector.cpp.o
.PHONY : battle/targetSelector.cpp.o

battle/targetSelector.i: battle/targetSelector.cpp.i
.PHONY : battle/targetSelector.i

# target to preprocess a source file
battle/targetSelector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/targetSelector.cpp.i
.PHONY : battle/targetSelector.cpp.i

battle/targetSelector.s: battle/targetSelector.cpp.s
.PHONY : battle/targetSelector.s

# target to generate assembly for a file
battle/targetSelector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/targetSelector.cpp.s
.PHONY : battle/targetSelector.cpp.s

battle/vfx.o: battle/vfx.cpp.o
.PHONY : battle/vfx.o

# target to build an object file
battle/vfx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/vfx.cpp.o
.PHONY : battle/vfx.cpp.o

battle/vfx.i: battle/vfx.cpp.i
.PHONY : battle/vfx.i

# target to preprocess a source file
battle/vfx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/vfx.cpp.i
.PHONY : battle/vfx.cpp.i

battle/vfx.s: battle/vfx.cpp.s
.PHONY : battle/vfx.s

# target to generate assembly for a file
battle/vfx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/vfx.cpp.s
.PHONY : battle/vfx.cpp.s

battle/vfxManager.o: battle/vfxManager.cpp.o
.PHONY : battle/vfxManager.o

# target to build an object file
battle/vfxManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/vfxManager.cpp.o
.PHONY : battle/vfxManager.cpp.o

battle/vfxManager.i: battle/vfxManager.cpp.i
.PHONY : battle/vfxManager.i

# target to preprocess a source file
battle/vfxManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/vfxManager.cpp.i
.PHONY : battle/vfxManager.cpp.i

battle/vfxManager.s: battle/vfxManager.cpp.s
.PHONY : battle/vfxManager.s

# target to generate assembly for a file
battle/vfxManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/battle/vfxManager.cpp.s
.PHONY : battle/vfxManager.cpp.s

core/game.o: core/game.cpp.o
.PHONY : core/game.o

# target to build an object file
core/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/game.cpp.o
.PHONY : core/game.cpp.o

core/game.i: core/game.cpp.i
.PHONY : core/game.i

# target to preprocess a source file
core/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/game.cpp.i
.PHONY : core/game.cpp.i

core/game.s: core/game.cpp.s
.PHONY : core/game.s

# target to generate assembly for a file
core/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/game.cpp.s
.PHONY : core/game.cpp.s

core/resourceManager.o: core/resourceManager.cpp.o
.PHONY : core/resourceManager.o

# target to build an object file
core/resourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/resourceManager.cpp.o
.PHONY : core/resourceManager.cpp.o

core/resourceManager.i: core/resourceManager.cpp.i
.PHONY : core/resourceManager.i

# target to preprocess a source file
core/resourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/resourceManager.cpp.i
.PHONY : core/resourceManager.cpp.i

core/resourceManager.s: core/resourceManager.cpp.s
.PHONY : core/resourceManager.s

# target to generate assembly for a file
core/resourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/resourceManager.cpp.s
.PHONY : core/resourceManager.cpp.s

core/stateManager.o: core/stateManager.cpp.o
.PHONY : core/stateManager.o

# target to build an object file
core/stateManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/stateManager.cpp.o
.PHONY : core/stateManager.cpp.o

core/stateManager.i: core/stateManager.cpp.i
.PHONY : core/stateManager.i

# target to preprocess a source file
core/stateManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/stateManager.cpp.i
.PHONY : core/stateManager.cpp.i

core/stateManager.s: core/stateManager.cpp.s
.PHONY : core/stateManager.s

# target to generate assembly for a file
core/stateManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/core/stateManager.cpp.s
.PHONY : core/stateManager.cpp.s

dialog/dialog.o: dialog/dialog.cpp.o
.PHONY : dialog/dialog.o

# target to build an object file
dialog/dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/dialog.cpp.o
.PHONY : dialog/dialog.cpp.o

dialog/dialog.i: dialog/dialog.cpp.i
.PHONY : dialog/dialog.i

# target to preprocess a source file
dialog/dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/dialog.cpp.i
.PHONY : dialog/dialog.cpp.i

dialog/dialog.s: dialog/dialog.cpp.s
.PHONY : dialog/dialog.s

# target to generate assembly for a file
dialog/dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/dialog.cpp.s
.PHONY : dialog/dialog.cpp.s

dialog/dialogPopup.o: dialog/dialogPopup.cpp.o
.PHONY : dialog/dialogPopup.o

# target to build an object file
dialog/dialogPopup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/dialogPopup.cpp.o
.PHONY : dialog/dialogPopup.cpp.o

dialog/dialogPopup.i: dialog/dialogPopup.cpp.i
.PHONY : dialog/dialogPopup.i

# target to preprocess a source file
dialog/dialogPopup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/dialogPopup.cpp.i
.PHONY : dialog/dialogPopup.cpp.i

dialog/dialogPopup.s: dialog/dialogPopup.cpp.s
.PHONY : dialog/dialogPopup.s

# target to generate assembly for a file
dialog/dialogPopup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/dialogPopup.cpp.s
.PHONY : dialog/dialogPopup.cpp.s

dialog/emotion.o: dialog/emotion.cpp.o
.PHONY : dialog/emotion.o

# target to build an object file
dialog/emotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/emotion.cpp.o
.PHONY : dialog/emotion.cpp.o

dialog/emotion.i: dialog/emotion.cpp.i
.PHONY : dialog/emotion.i

# target to preprocess a source file
dialog/emotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/emotion.cpp.i
.PHONY : dialog/emotion.cpp.i

dialog/emotion.s: dialog/emotion.cpp.s
.PHONY : dialog/emotion.s

# target to generate assembly for a file
dialog/emotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/emotion.cpp.s
.PHONY : dialog/emotion.cpp.s

dialog/typewritter.o: dialog/typewritter.cpp.o
.PHONY : dialog/typewritter.o

# target to build an object file
dialog/typewritter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/typewritter.cpp.o
.PHONY : dialog/typewritter.cpp.o

dialog/typewritter.i: dialog/typewritter.cpp.i
.PHONY : dialog/typewritter.i

# target to preprocess a source file
dialog/typewritter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/typewritter.cpp.i
.PHONY : dialog/typewritter.cpp.i

dialog/typewritter.s: dialog/typewritter.cpp.s
.PHONY : dialog/typewritter.s

# target to generate assembly for a file
dialog/typewritter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/dialog/typewritter.cpp.s
.PHONY : dialog/typewritter.cpp.s

entities/player.o: entities/player.cpp.o
.PHONY : entities/player.o

# target to build an object file
entities/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/player.cpp.o
.PHONY : entities/player.cpp.o

entities/player.i: entities/player.cpp.i
.PHONY : entities/player.i

# target to preprocess a source file
entities/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/player.cpp.i
.PHONY : entities/player.cpp.i

entities/player.s: entities/player.cpp.s
.PHONY : entities/player.s

# target to generate assembly for a file
entities/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/player.cpp.s
.PHONY : entities/player.cpp.s

entities/spriteV2.o: entities/spriteV2.cpp.o
.PHONY : entities/spriteV2.o

# target to build an object file
entities/spriteV2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/spriteV2.cpp.o
.PHONY : entities/spriteV2.cpp.o

entities/spriteV2.i: entities/spriteV2.cpp.i
.PHONY : entities/spriteV2.i

# target to preprocess a source file
entities/spriteV2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/spriteV2.cpp.i
.PHONY : entities/spriteV2.cpp.i

entities/spriteV2.s: entities/spriteV2.cpp.s
.PHONY : entities/spriteV2.s

# target to generate assembly for a file
entities/spriteV2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/spriteV2.cpp.s
.PHONY : entities/spriteV2.cpp.s

entities/tree.o: entities/tree.cpp.o
.PHONY : entities/tree.o

# target to build an object file
entities/tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/tree.cpp.o
.PHONY : entities/tree.cpp.o

entities/tree.i: entities/tree.cpp.i
.PHONY : entities/tree.i

# target to preprocess a source file
entities/tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/tree.cpp.i
.PHONY : entities/tree.cpp.i

entities/tree.s: entities/tree.cpp.s
.PHONY : entities/tree.s

# target to generate assembly for a file
entities/tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/tree.cpp.s
.PHONY : entities/tree.cpp.s

entities/uniqueHitbox.o: entities/uniqueHitbox.cpp.o
.PHONY : entities/uniqueHitbox.o

# target to build an object file
entities/uniqueHitbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/uniqueHitbox.cpp.o
.PHONY : entities/uniqueHitbox.cpp.o

entities/uniqueHitbox.i: entities/uniqueHitbox.cpp.i
.PHONY : entities/uniqueHitbox.i

# target to preprocess a source file
entities/uniqueHitbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/uniqueHitbox.cpp.i
.PHONY : entities/uniqueHitbox.cpp.i

entities/uniqueHitbox.s: entities/uniqueHitbox.cpp.s
.PHONY : entities/uniqueHitbox.s

# target to generate assembly for a file
entities/uniqueHitbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/entities/uniqueHitbox.cpp.s
.PHONY : entities/uniqueHitbox.cpp.s

gui/button.o: gui/button.cpp.o
.PHONY : gui/button.o

# target to build an object file
gui/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/button.cpp.o
.PHONY : gui/button.cpp.o

gui/button.i: gui/button.cpp.i
.PHONY : gui/button.i

# target to preprocess a source file
gui/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/button.cpp.i
.PHONY : gui/button.cpp.i

gui/button.s: gui/button.cpp.s
.PHONY : gui/button.s

# target to generate assembly for a file
gui/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/button.cpp.s
.PHONY : gui/button.cpp.s

gui/buttonList.o: gui/buttonList.cpp.o
.PHONY : gui/buttonList.o

# target to build an object file
gui/buttonList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/buttonList.cpp.o
.PHONY : gui/buttonList.cpp.o

gui/buttonList.i: gui/buttonList.cpp.i
.PHONY : gui/buttonList.i

# target to preprocess a source file
gui/buttonList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/buttonList.cpp.i
.PHONY : gui/buttonList.cpp.i

gui/buttonList.s: gui/buttonList.cpp.s
.PHONY : gui/buttonList.s

# target to generate assembly for a file
gui/buttonList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/buttonList.cpp.s
.PHONY : gui/buttonList.cpp.s

gui/gui.o: gui/gui.cpp.o
.PHONY : gui/gui.o

# target to build an object file
gui/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/gui.cpp.o
.PHONY : gui/gui.cpp.o

gui/gui.i: gui/gui.cpp.i
.PHONY : gui/gui.i

# target to preprocess a source file
gui/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/gui.cpp.i
.PHONY : gui/gui.cpp.i

gui/gui.s: gui/gui.cpp.s
.PHONY : gui/gui.s

# target to generate assembly for a file
gui/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/gui.cpp.s
.PHONY : gui/gui.cpp.s

gui/guiManager.o: gui/guiManager.cpp.o
.PHONY : gui/guiManager.o

# target to build an object file
gui/guiManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/guiManager.cpp.o
.PHONY : gui/guiManager.cpp.o

gui/guiManager.i: gui/guiManager.cpp.i
.PHONY : gui/guiManager.i

# target to preprocess a source file
gui/guiManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/guiManager.cpp.i
.PHONY : gui/guiManager.cpp.i

gui/guiManager.s: gui/guiManager.cpp.s
.PHONY : gui/guiManager.s

# target to generate assembly for a file
gui/guiManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/guiManager.cpp.s
.PHONY : gui/guiManager.cpp.s

gui/window.o: gui/window.cpp.o
.PHONY : gui/window.o

# target to build an object file
gui/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/window.cpp.o
.PHONY : gui/window.cpp.o

gui/window.i: gui/window.cpp.i
.PHONY : gui/window.i

# target to preprocess a source file
gui/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/window.cpp.i
.PHONY : gui/window.cpp.i

gui/window.s: gui/window.cpp.s
.PHONY : gui/window.s

# target to generate assembly for a file
gui/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/gui/window.cpp.s
.PHONY : gui/window.cpp.s

item/inventory.o: item/inventory.cpp.o
.PHONY : item/inventory.o

# target to build an object file
item/inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/inventory.cpp.o
.PHONY : item/inventory.cpp.o

item/inventory.i: item/inventory.cpp.i
.PHONY : item/inventory.i

# target to preprocess a source file
item/inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/inventory.cpp.i
.PHONY : item/inventory.cpp.i

item/inventory.s: item/inventory.cpp.s
.PHONY : item/inventory.s

# target to generate assembly for a file
item/inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/inventory.cpp.s
.PHONY : item/inventory.cpp.s

item/inventoryContainer.o: item/inventoryContainer.cpp.o
.PHONY : item/inventoryContainer.o

# target to build an object file
item/inventoryContainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/inventoryContainer.cpp.o
.PHONY : item/inventoryContainer.cpp.o

item/inventoryContainer.i: item/inventoryContainer.cpp.i
.PHONY : item/inventoryContainer.i

# target to preprocess a source file
item/inventoryContainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/inventoryContainer.cpp.i
.PHONY : item/inventoryContainer.cpp.i

item/inventoryContainer.s: item/inventoryContainer.cpp.s
.PHONY : item/inventoryContainer.s

# target to generate assembly for a file
item/inventoryContainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/inventoryContainer.cpp.s
.PHONY : item/inventoryContainer.cpp.s

item/itemManager.o: item/itemManager.cpp.o
.PHONY : item/itemManager.o

# target to build an object file
item/itemManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/itemManager.cpp.o
.PHONY : item/itemManager.cpp.o

item/itemManager.i: item/itemManager.cpp.i
.PHONY : item/itemManager.i

# target to preprocess a source file
item/itemManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/itemManager.cpp.i
.PHONY : item/itemManager.cpp.i

item/itemManager.s: item/itemManager.cpp.s
.PHONY : item/itemManager.s

# target to generate assembly for a file
item/itemManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/item/itemManager.cpp.s
.PHONY : item/itemManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/main.cpp.s
.PHONY : main.cpp.s

map/mapEntity.o: map/mapEntity.cpp.o
.PHONY : map/mapEntity.o

# target to build an object file
map/mapEntity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapEntity.cpp.o
.PHONY : map/mapEntity.cpp.o

map/mapEntity.i: map/mapEntity.cpp.i
.PHONY : map/mapEntity.i

# target to preprocess a source file
map/mapEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapEntity.cpp.i
.PHONY : map/mapEntity.cpp.i

map/mapEntity.s: map/mapEntity.cpp.s
.PHONY : map/mapEntity.s

# target to generate assembly for a file
map/mapEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapEntity.cpp.s
.PHONY : map/mapEntity.cpp.s

map/mapItem.o: map/mapItem.cpp.o
.PHONY : map/mapItem.o

# target to build an object file
map/mapItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapItem.cpp.o
.PHONY : map/mapItem.cpp.o

map/mapItem.i: map/mapItem.cpp.i
.PHONY : map/mapItem.i

# target to preprocess a source file
map/mapItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapItem.cpp.i
.PHONY : map/mapItem.cpp.i

map/mapItem.s: map/mapItem.cpp.s
.PHONY : map/mapItem.s

# target to generate assembly for a file
map/mapItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapItem.cpp.s
.PHONY : map/mapItem.cpp.s

map/mapItemManager.o: map/mapItemManager.cpp.o
.PHONY : map/mapItemManager.o

# target to build an object file
map/mapItemManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapItemManager.cpp.o
.PHONY : map/mapItemManager.cpp.o

map/mapItemManager.i: map/mapItemManager.cpp.i
.PHONY : map/mapItemManager.i

# target to preprocess a source file
map/mapItemManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapItemManager.cpp.i
.PHONY : map/mapItemManager.cpp.i

map/mapItemManager.s: map/mapItemManager.cpp.s
.PHONY : map/mapItemManager.s

# target to generate assembly for a file
map/mapItemManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/mapItemManager.cpp.s
.PHONY : map/mapItemManager.cpp.s

map/npc.o: map/npc.cpp.o
.PHONY : map/npc.o

# target to build an object file
map/npc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/npc.cpp.o
.PHONY : map/npc.cpp.o

map/npc.i: map/npc.cpp.i
.PHONY : map/npc.i

# target to preprocess a source file
map/npc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/npc.cpp.i
.PHONY : map/npc.cpp.i

map/npc.s: map/npc.cpp.s
.PHONY : map/npc.s

# target to generate assembly for a file
map/npc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/npc.cpp.s
.PHONY : map/npc.cpp.s

map/npcManager.o: map/npcManager.cpp.o
.PHONY : map/npcManager.o

# target to build an object file
map/npcManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/npcManager.cpp.o
.PHONY : map/npcManager.cpp.o

map/npcManager.i: map/npcManager.cpp.i
.PHONY : map/npcManager.i

# target to preprocess a source file
map/npcManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/npcManager.cpp.i
.PHONY : map/npcManager.cpp.i

map/npcManager.s: map/npcManager.cpp.s
.PHONY : map/npcManager.s

# target to generate assembly for a file
map/npcManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/npcManager.cpp.s
.PHONY : map/npcManager.cpp.s

map/tileTrigger.o: map/tileTrigger.cpp.o
.PHONY : map/tileTrigger.o

# target to build an object file
map/tileTrigger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/tileTrigger.cpp.o
.PHONY : map/tileTrigger.cpp.o

map/tileTrigger.i: map/tileTrigger.cpp.i
.PHONY : map/tileTrigger.i

# target to preprocess a source file
map/tileTrigger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/tileTrigger.cpp.i
.PHONY : map/tileTrigger.cpp.i

map/tileTrigger.s: map/tileTrigger.cpp.s
.PHONY : map/tileTrigger.s

# target to generate assembly for a file
map/tileTrigger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/map/tileTrigger.cpp.s
.PHONY : map/tileTrigger.cpp.s

misc/configReader.o: misc/configReader.cpp.o
.PHONY : misc/configReader.o

# target to build an object file
misc/configReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/configReader.cpp.o
.PHONY : misc/configReader.cpp.o

misc/configReader.i: misc/configReader.cpp.i
.PHONY : misc/configReader.i

# target to preprocess a source file
misc/configReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/configReader.cpp.i
.PHONY : misc/configReader.cpp.i

misc/configReader.s: misc/configReader.cpp.s
.PHONY : misc/configReader.s

# target to generate assembly for a file
misc/configReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/configReader.cpp.s
.PHONY : misc/configReader.cpp.s

misc/floatingText.o: misc/floatingText.cpp.o
.PHONY : misc/floatingText.o

# target to build an object file
misc/floatingText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/floatingText.cpp.o
.PHONY : misc/floatingText.cpp.o

misc/floatingText.i: misc/floatingText.cpp.i
.PHONY : misc/floatingText.i

# target to preprocess a source file
misc/floatingText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/floatingText.cpp.i
.PHONY : misc/floatingText.cpp.i

misc/floatingText.s: misc/floatingText.cpp.s
.PHONY : misc/floatingText.s

# target to generate assembly for a file
misc/floatingText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/floatingText.cpp.s
.PHONY : misc/floatingText.cpp.s

misc/ghostTrail.o: misc/ghostTrail.cpp.o
.PHONY : misc/ghostTrail.o

# target to build an object file
misc/ghostTrail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/ghostTrail.cpp.o
.PHONY : misc/ghostTrail.cpp.o

misc/ghostTrail.i: misc/ghostTrail.cpp.i
.PHONY : misc/ghostTrail.i

# target to preprocess a source file
misc/ghostTrail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/ghostTrail.cpp.i
.PHONY : misc/ghostTrail.cpp.i

misc/ghostTrail.s: misc/ghostTrail.cpp.s
.PHONY : misc/ghostTrail.s

# target to generate assembly for a file
misc/ghostTrail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/ghostTrail.cpp.s
.PHONY : misc/ghostTrail.cpp.s

misc/mapGenerator.o: misc/mapGenerator.cpp.o
.PHONY : misc/mapGenerator.o

# target to build an object file
misc/mapGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/mapGenerator.cpp.o
.PHONY : misc/mapGenerator.cpp.o

misc/mapGenerator.i: misc/mapGenerator.cpp.i
.PHONY : misc/mapGenerator.i

# target to preprocess a source file
misc/mapGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/mapGenerator.cpp.i
.PHONY : misc/mapGenerator.cpp.i

misc/mapGenerator.s: misc/mapGenerator.cpp.s
.PHONY : misc/mapGenerator.s

# target to generate assembly for a file
misc/mapGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/mapGenerator.cpp.s
.PHONY : misc/mapGenerator.cpp.s

misc/text.o: misc/text.cpp.o
.PHONY : misc/text.o

# target to build an object file
misc/text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/text.cpp.o
.PHONY : misc/text.cpp.o

misc/text.i: misc/text.cpp.i
.PHONY : misc/text.i

# target to preprocess a source file
misc/text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/text.cpp.i
.PHONY : misc/text.cpp.i

misc/text.s: misc/text.cpp.s
.PHONY : misc/text.s

# target to generate assembly for a file
misc/text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/misc/text.cpp.s
.PHONY : misc/text.cpp.s

states/battleState.o: states/battleState.cpp.o
.PHONY : states/battleState.o

# target to build an object file
states/battleState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/battleState.cpp.o
.PHONY : states/battleState.cpp.o

states/battleState.i: states/battleState.cpp.i
.PHONY : states/battleState.i

# target to preprocess a source file
states/battleState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/battleState.cpp.i
.PHONY : states/battleState.cpp.i

states/battleState.s: states/battleState.cpp.s
.PHONY : states/battleState.s

# target to generate assembly for a file
states/battleState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/battleState.cpp.s
.PHONY : states/battleState.cpp.s

states/mapState.o: states/mapState.cpp.o
.PHONY : states/mapState.o

# target to build an object file
states/mapState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/mapState.cpp.o
.PHONY : states/mapState.cpp.o

states/mapState.i: states/mapState.cpp.i
.PHONY : states/mapState.i

# target to preprocess a source file
states/mapState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/mapState.cpp.i
.PHONY : states/mapState.cpp.i

states/mapState.s: states/mapState.cpp.s
.PHONY : states/mapState.s

# target to generate assembly for a file
states/mapState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/mapState.cpp.s
.PHONY : states/mapState.cpp.s

states/menuState.o: states/menuState.cpp.o
.PHONY : states/menuState.o

# target to build an object file
states/menuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/menuState.cpp.o
.PHONY : states/menuState.cpp.o

states/menuState.i: states/menuState.cpp.i
.PHONY : states/menuState.i

# target to preprocess a source file
states/menuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/menuState.cpp.i
.PHONY : states/menuState.cpp.i

states/menuState.s: states/menuState.cpp.s
.PHONY : states/menuState.s

# target to generate assembly for a file
states/menuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/menuState.cpp.s
.PHONY : states/menuState.cpp.s

states/sceneState.o: states/sceneState.cpp.o
.PHONY : states/sceneState.o

# target to build an object file
states/sceneState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/sceneState.cpp.o
.PHONY : states/sceneState.cpp.o

states/sceneState.i: states/sceneState.cpp.i
.PHONY : states/sceneState.i

# target to preprocess a source file
states/sceneState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/sceneState.cpp.i
.PHONY : states/sceneState.cpp.i

states/sceneState.s: states/sceneState.cpp.s
.PHONY : states/sceneState.s

# target to generate assembly for a file
states/sceneState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\5bw12.dir\build.make CMakeFiles/5bw12.dir/states/sceneState.cpp.s
.PHONY : states/sceneState.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... 5bw12
	@echo ... battle/ability.o
	@echo ... battle/ability.i
	@echo ... battle/ability.s
	@echo ... battle/abilityManager.o
	@echo ... battle/abilityManager.i
	@echo ... battle/abilityManager.s
	@echo ... battle/abilityPanel.o
	@echo ... battle/abilityPanel.i
	@echo ... battle/abilityPanel.s
	@echo ... battle/actionText.o
	@echo ... battle/actionText.i
	@echo ... battle/actionText.s
	@echo ... battle/battleEntity.o
	@echo ... battle/battleEntity.i
	@echo ... battle/battleEntity.s
	@echo ... battle/bulletEntity.o
	@echo ... battle/bulletEntity.i
	@echo ... battle/bulletEntity.s
	@echo ... battle/cardVfx.o
	@echo ... battle/cardVfx.i
	@echo ... battle/cardVfx.s
	@echo ... battle/effectIcon.o
	@echo ... battle/effectIcon.i
	@echo ... battle/effectIcon.s
	@echo ... battle/effectIconList.o
	@echo ... battle/effectIconList.i
	@echo ... battle/effectIconList.s
	@echo ... battle/effectLabel.o
	@echo ... battle/effectLabel.i
	@echo ... battle/effectLabel.s
	@echo ... battle/enemyParty.o
	@echo ... battle/enemyParty.i
	@echo ... battle/enemyParty.s
	@echo ... battle/minigame.o
	@echo ... battle/minigame.i
	@echo ... battle/minigame.s
	@echo ... battle/party.o
	@echo ... battle/party.i
	@echo ... battle/party.s
	@echo ... battle/partyManager.o
	@echo ... battle/partyManager.i
	@echo ... battle/partyManager.s
	@echo ... battle/playerParty.o
	@echo ... battle/playerParty.i
	@echo ... battle/playerParty.s
	@echo ... battle/targetSelector.o
	@echo ... battle/targetSelector.i
	@echo ... battle/targetSelector.s
	@echo ... battle/vfx.o
	@echo ... battle/vfx.i
	@echo ... battle/vfx.s
	@echo ... battle/vfxManager.o
	@echo ... battle/vfxManager.i
	@echo ... battle/vfxManager.s
	@echo ... core/game.o
	@echo ... core/game.i
	@echo ... core/game.s
	@echo ... core/resourceManager.o
	@echo ... core/resourceManager.i
	@echo ... core/resourceManager.s
	@echo ... core/stateManager.o
	@echo ... core/stateManager.i
	@echo ... core/stateManager.s
	@echo ... dialog/dialog.o
	@echo ... dialog/dialog.i
	@echo ... dialog/dialog.s
	@echo ... dialog/dialogPopup.o
	@echo ... dialog/dialogPopup.i
	@echo ... dialog/dialogPopup.s
	@echo ... dialog/emotion.o
	@echo ... dialog/emotion.i
	@echo ... dialog/emotion.s
	@echo ... dialog/typewritter.o
	@echo ... dialog/typewritter.i
	@echo ... dialog/typewritter.s
	@echo ... entities/player.o
	@echo ... entities/player.i
	@echo ... entities/player.s
	@echo ... entities/spriteV2.o
	@echo ... entities/spriteV2.i
	@echo ... entities/spriteV2.s
	@echo ... entities/tree.o
	@echo ... entities/tree.i
	@echo ... entities/tree.s
	@echo ... entities/uniqueHitbox.o
	@echo ... entities/uniqueHitbox.i
	@echo ... entities/uniqueHitbox.s
	@echo ... gui/button.o
	@echo ... gui/button.i
	@echo ... gui/button.s
	@echo ... gui/buttonList.o
	@echo ... gui/buttonList.i
	@echo ... gui/buttonList.s
	@echo ... gui/gui.o
	@echo ... gui/gui.i
	@echo ... gui/gui.s
	@echo ... gui/guiManager.o
	@echo ... gui/guiManager.i
	@echo ... gui/guiManager.s
	@echo ... gui/window.o
	@echo ... gui/window.i
	@echo ... gui/window.s
	@echo ... item/inventory.o
	@echo ... item/inventory.i
	@echo ... item/inventory.s
	@echo ... item/inventoryContainer.o
	@echo ... item/inventoryContainer.i
	@echo ... item/inventoryContainer.s
	@echo ... item/itemManager.o
	@echo ... item/itemManager.i
	@echo ... item/itemManager.s
	@echo ... main.o
	@echo ... main.i
	@echo ... main.s
	@echo ... map/mapEntity.o
	@echo ... map/mapEntity.i
	@echo ... map/mapEntity.s
	@echo ... map/mapItem.o
	@echo ... map/mapItem.i
	@echo ... map/mapItem.s
	@echo ... map/mapItemManager.o
	@echo ... map/mapItemManager.i
	@echo ... map/mapItemManager.s
	@echo ... map/npc.o
	@echo ... map/npc.i
	@echo ... map/npc.s
	@echo ... map/npcManager.o
	@echo ... map/npcManager.i
	@echo ... map/npcManager.s
	@echo ... map/tileTrigger.o
	@echo ... map/tileTrigger.i
	@echo ... map/tileTrigger.s
	@echo ... misc/configReader.o
	@echo ... misc/configReader.i
	@echo ... misc/configReader.s
	@echo ... misc/floatingText.o
	@echo ... misc/floatingText.i
	@echo ... misc/floatingText.s
	@echo ... misc/ghostTrail.o
	@echo ... misc/ghostTrail.i
	@echo ... misc/ghostTrail.s
	@echo ... misc/mapGenerator.o
	@echo ... misc/mapGenerator.i
	@echo ... misc/mapGenerator.s
	@echo ... misc/text.o
	@echo ... misc/text.i
	@echo ... misc/text.s
	@echo ... states/battleState.o
	@echo ... states/battleState.i
	@echo ... states/battleState.s
	@echo ... states/mapState.o
	@echo ... states/mapState.i
	@echo ... states/mapState.s
	@echo ... states/menuState.o
	@echo ... states/menuState.i
	@echo ... states/menuState.s
	@echo ... states/sceneState.o
	@echo ... states/sceneState.i
	@echo ... states/sceneState.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

