/**
 * @file targetSelector.h
 * @author askar102
 * @brief Target selection system — cursor circle + hitbox outline on hover, callback on confirm
 * @date 2026-05-30
 *
 * @copyright Copyright (c) 2026, askar102
 *
 */

// GENERATED BY CLAUDE, NOT FUCKING ME, I WILL REWORK THIS IN PAST 


 #pragma once

 #include <functional>
 #include <vector>
 
 #include "../raylib/raylib.h"
 #include "battleEntity.h"
 
 // Описание одной таргет-абилки: что делать при подтверждении цели.
 // Добавляешь новую абилку — просто регистрируешь новый коллбек через Arm().
 struct TargetAbilityDesc {
     // Вызывается когда игрок кликнул на цель.
     // caster  — кто использует абилку
     // target  — на кого направлена
     std::function<void(BattleEntity& caster, BattleEntity& target)> onConfirm;
 
     // Вызывается если игрок отменил выбор (Escape / правая кнопка).
     // Можно оставить nullptr.
     std::function<void()> onCancel;
 };
 
 class TargetSelector {
 public:
     // Активировать режим выбора цели.
     // caster       — кто кастует
     // targets      — список ВСЕХ потенциальных целей (союзники + враги — не важно)
     // desc         — что делать при выборе/отмене
     // Во время выбора у всех targets canSelected = false, вернём обратно на выходе.
     void Arm(BattleEntity* caster,
              std::vector<BattleEntity*> targets,
              TargetAbilityDesc desc);
 
     // Деактивировать без подтверждения (вызывает onCancel если задан).
     void Cancel();
 
     bool IsActive() const { return _active; }
 
     // Вызывать каждый кадр из BattleState::HandleInput() / Update().
     // mouse — текущая позиция мыши.
     // Возвращает true если в этом кадре произошло подтверждение или отмена
     // (после этого IsActive() == false).
     bool HandleInput(Vector2 mouse);
 
     // Рисует курсор-кружок и контур вокруг цели под мышкой.
     void Draw(Vector2 mouse) const;
 
 private:
     bool _active = false;
 
     BattleEntity* _caster = nullptr;
     std::vector<BattleEntity*> _targets;
     TargetAbilityDesc _desc;
 
     // Восстанавливаем canSelected после завершения
     void RestoreTargets();
 
     // Найти цель под мышкой (по хитбоксу)
     BattleEntity* FindHovered(Vector2 mouse) const;
 
     static constexpr float CURSOR_RADIUS   = 10.0f;
     static constexpr float OUTLINE_PADDING =  4.0f;
     static constexpr Color CURSOR_COLOR    = { 255, 255,   0, 200 };
     static constexpr Color OUTLINE_COLOR   = { 255, 255,   0, 180 };
 };